// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhv8uqLnPIP6FVFqXbynUlY-XK2WxCzDU',
    appId: '1:1093795560242:web:a6ec23a5d81a164fb5b52b',
    messagingSenderId: '1093795560242',
    projectId: 'risetimedev2022',
    authDomain: 'risetimedev2022.firebaseapp.com',
    storageBucket: 'risetimedev2022.appspot.com',
    measurementId: 'G-S62E2ZN25L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEGknAXjuyNDOsw0K0nha7HRR3oU--Z0',
    appId: '1:1093795560242:android:dd849a18441834adb5b52b',
    messagingSenderId: '1093795560242',
    projectId: 'risetimedev2022',
    storageBucket: 'risetimedev2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMQGANdGs2oOqDScaKeoXpjtO_1PmqhkU',
    appId: '1:1093795560242:ios:faf92e8fcd173d0bb5b52b',
    messagingSenderId: '1093795560242',
    projectId: 'risetimedev2022',
    storageBucket: 'risetimedev2022.appspot.com',
    iosClientId: '1093795560242-eadljcgv7d6f49fdg3iqkinjp6o6tkv0.apps.googleusercontent.com',
    iosBundleId: 'com.piteknoloji.risetimedev',
  );
}
